import { useEffect, useRef, useState, type ReactNode } from 'react'
import { motion, useReducedMotion } from 'motion/react'
import { abilityText, actor, campTypes, colors, pearlPoints, slotLabel, type Fairy, type Game, type Pearl, type Slot, type Villager } from './game'
import { assetUrl } from './assets'
import { boardLayout } from './boardLayout'
import { CampCard, campInfo } from './CampCard'
import { fairySymbol, RiverBoard } from './RiverBoard'
import { fairyEffects, preparationGame, preparationStep, type Presentation } from './presentation'

const tribes = ['#c8795b', '#518f91', '#c39b43', '#9d82b2']
type Props = { game: Game; readOnly?: boolean; presentation: Presentation | null; animations: boolean; setAnimations: (value: boolean) => void; finish: () => void; legal: Set<string>; choose: (slot: Slot) => void; recruit: (id: string) => void; selectedPearl: number | null; onPearlSelect?: (index: number) => void; actions: ReactNode; renderVillager: (villager: Villager, interactive: boolean) => ReactNode; selectCargo: (index: number) => void; navigation: ReactNode; guide: ReactNode; scores: ReactNode; error: string }
function PearlChip({ color, open = false }: { color: Pearl | 'any'; open?: boolean }) { return <span className={`pearl ${color} ${open ? 'open' : ''}`} title={open ? `Empty ${color} socket` : `${color} · ${color === 'any' ? 'wild' : pearlPoints[color]} points`}/> }
function Card({ villager: v, selected = false, children }: { villager: Villager; selected?: boolean; children?: ReactNode }) {
  return <article className={`scene-villager ${selected ? 'selected' : ''}`} data-villager={v.id}><img src={assetUrl(v.portrait)} alt={`${v.name} portrait`}/><div className="scene-card-name"><strong>{v.name}</strong><small title="Camp cards gained when recruited">▱ {v.reward}</small></div><p>{abilityText[v.ability]}</p><div className="scene-sockets">{v.sockets.map((color, i) => <PearlChip key={i} color={v.stored[i] ?? (v.wild.includes(i) ? 'any' : color)} open={!v.stored[i]}/>)}</div>{children}</article>
}
function readExpanded(gameId: string): number | null { try { const value = localStorage.getItem(`rivers-column-${gameId}`); return value === null ? null : JSON.parse(value) } catch { return null } }

export function BoardScene(props: Props) {
  const { game: input, presentation, animations, finish } = props
  const game = presentation?.preparation ? preparationGame(presentation) : input, step = preparationStep(presentation), reduced = !!useReducedMotion() || !animations
  const [expanded, setExpanded] = useState<number | null>(() => readExpanded(input.id))
  const [comparison, setComparison] = useState<string | null>(null)
  const [detail, setDetail] = useState<string | null>(null)
  const [fairy, setFairy] = useState<Fairy | null>(null)
  const [panel, setPanel] = useState<'actions' | 'settings' | 'guide' | 'camp' | null>(null)
  const [goal, setGoal] = useState<string | null>(null)
  const root = useRef<HTMLDivElement>(null), compareClose = useRef<HTMLButtonElement>(null), priorFocus = useRef<HTMLElement | null>(null)
  const who = actor(input), player = game.players[expanded ?? -1], preparing = !!presentation?.preparation
  const humanTurn = !props.readOnly && who !== null && !input.players[who].bot
  useEffect(() => {
    if (!preparing && humanTurn && ((!['explore', 'finished'].includes(input.phase)) || input.afterPlace || input.pendingDraws)) setPanel('actions')
    else setPanel(null)
  }, [input.phase, input.afterPlace, !!input.pendingDraws, who, preparing])
  useEffect(() => { try { localStorage.setItem(`rivers-column-${input.id}`, JSON.stringify(expanded)) } catch { /* A private browser may disable storage. */ } }, [input.id, expanded])
  useEffect(() => {
    if (!comparison) return
    priorFocus.current = document.activeElement as HTMLElement; compareClose.current?.focus()
    return () => priorFocus.current?.focus()
  }, [!!comparison])
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { setComparison(null); setPanel(null); setFairy(null); setDetail(null); setGoal(null) }
      if (event.key === 'Tab' && comparison) {
        const controls = Array.from(root.current?.querySelectorAll<HTMLElement>('.comparison button') ?? [])
        if (!controls.length) return
        const first = controls[0], last = controls.at(-1)!
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() }
        if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() }
      }
    }
    window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey)
  }, [comparison])
  useEffect(() => {
    const element = root.current; if (!element) return
    const resize = () => { const rect = element.getBoundingClientRect(); const width = element.querySelector('.scene-board')!.getBoundingClientRect().width; element.style.setProperty('--hit-radius', `${Math.max(27, 22 / Math.min(width / 1532, rect.height / 1080))}px`) }
    const observer = new ResizeObserver(resize); observer.observe(element); resize(); return () => observer.disconnect()
  }, [])
  function expand(id: number) { setExpanded(id); setDetail(null); setFairy(null) }
  function mat(id: number, selected = false) {
    const p = game.players[id], caught = presentation?.caught?.player === id ? presentation.caught : undefined
    const cargo = caught ? presentation!.after.players[id].alpaca : p.alpaca
    return <section key={id} data-player-mat={id} className={`llama-mat ${who === id ? 'current' : ''}`} style={{ '--tribe': tribes[id] } as React.CSSProperties}>
      <h2><i/>{p.name}<small>{p.bot ? 'BOT' : ''}</small></h2>
      {selected ? <button className="minimize-rail" aria-label="Minimize player column and show all llamas" onClick={() => { setExpanded(null); setDetail(null); setFairy(null) }}>−</button> : <button className="expand-mat" aria-label={`Expand ${p.name}'s llama`} onClick={() => expand(id)}/>}
      <img className="scene-llama" src={assetUrl('/board/llama.png')} alt="Cream llama facing left"/>
      <div className="llama-pearls">{Array.from({ length: 6 }, (_, i) => <button key={i} data-flight-target={`player-${id}-llama-${i}`} aria-label={`${p.name}, pearl ${i + 1}: ${cargo[i] ?? 'empty'}`} aria-pressed={who === id && props.selectedPearl === i} disabled={!!presentation || !humanTurn || id !== who || input.phase !== 'deliver' || !cargo[i]} onClick={() => { expand(id); props.selectCargo(i) }}><PearlChip color={cargo[i] ?? 'white'} open={!cargo[i] || caught?.socket === i}/></button>)}</div>
      <div className="mat-controls"><button onClick={() => expand(id)} aria-label={p.bot ? `${p.hand.length} hidden Camp cards. Expand player.` : `View ${p.name}'s Camp cards`}>{p.bot ? '🔒 ' : ''}Cards {p.hand.length}</button><button onClick={() => expand(id)}>Villagers {p.villagers.length}</button></div>
      <div className="mat-footer"><span>✦ {p.fairies.length} Faeries</span><span>Goals {p.goals.length}</span></div>
    </section>
  }
  const showActions = !preparing && !comparison && panel === 'actions'
  const focusCards = step?.kind === 'deal' ? presentation!.after.display.slice(0, step.count) : presentation?.after.display ?? []
  const stageMessage = presentation?.message ?? (who !== null ? `${input.players[who].name}${input.players[who].bot ? ' is thinking' : ' · ' + (input.phase === 'explore' ? 'place a Tribe token' : input.phase === 'deliver' ? 'deliver pearls' : 'choose your next action')}` : 'Journey complete')
  return <main ref={root} className="board-scene" data-preparation={step?.kind ?? ''} data-presentation={presentation?.id ?? ''}>
    <section className="scene-board" style={{ backgroundImage: `url(${assetUrl(boardLayout(game.players.length).background)})` }}>
      <RiverBoard game={input} legal={presentation || comparison ? new Set() : props.legal} choose={props.choose} presentation={presentation} animations={animations} selectedPearl={props.selectedPearl} onPearlSelect={comparison ? undefined : props.onPearlSelect}/>
      <nav className="scene-menu" aria-label="Game menu"><strong>WILD RIVERS</strong><span>Round {game.round} / 5</span><button onClick={() => { setPanel(null); setComparison(null) }}>Map</button><button onClick={() => setComparison(game.display[0]?.id ?? 'all')}>Villagers</button><button onClick={() => setPanel(panel === 'camp' ? null : 'camp')}>Camp</button><span className="scene-phase">{preparing ? 'Preparation' : input.phase === 'explore' ? 'Exploration' : input.phase === 'finished' ? 'Scoring' : 'Collection'}</span><button aria-label="Game settings" onClick={() => setPanel(panel === 'settings' ? null : 'settings')}>⚙</button></nav>
      <div className="scene-goals">{game.goals.map(g => <button key={g.id} className={g.owner !== null ? 'claimed' : ''} aria-label={`${g.title}: ${g.needs.length} ${g.needs[0]} pearls on your llama, worth 4 points. ${g.owner === null ? 'Available' : `Claimed by ${game.players[g.owner].name}`}`} onFocus={() => setGoal(g.id)} onBlur={() => setGoal(null)} onClick={() => setGoal(g.id)} title={`${g.title}: ${g.needs.length} ${g.needs[0]} pearls on your llama · 4 points`}><PearlChip color={g.needs[0]}/><b>{g.needs.length}</b></button>)}</div>
      {goal && <div className="goal-popover">{game.goals.filter(g => g.id === goal).map(g => <div key={g.id}><strong>{g.title}</strong><p>Carry {g.needs.length} {g.needs[0]} pearls on your llama. First to qualify claims 4 points at game end.</p><p>{g.owner === null ? 'Available' : `Claimed by ${game.players[g.owner].name}`}</p></div>)}</div>}
      <div className="scene-status" role="status" aria-live="polite">{stageMessage}</div>
      <div className="scene-villager-deck" title={`${game.villagerDeck.length} villagers in deck`}>♧</div>
      <h3 className="market-heading">Villagers</h3><div className="scene-market">{Array.from({ length: 6 }, (_, i) => { const v = game.display[i]; return v && step?.kind !== 'settle' ? <button key={v.id} data-market-villager={v.id} aria-label={`Compare available villagers: ${v.name}`} onClick={() => setComparison(v.id)}><img src={assetUrl(v.portrait)} alt={v.name}/><small>▱ {v.reward}</small><strong>{v.name}</strong></button> : <div key={i} className="empty-market"/> })}</div>
      <h3 className="village-heading">Village</h3>
      <div className="scene-track" aria-label={`Prepared turn order: ${game.track.map(id => game.players[id].name).join(', ')}`}><strong>Turn order</strong>{Array.from({ length: 12 }, (_, i) => { const offset = game.phase === 'explore' ? 0 : game.players.length * 3 - game.track.length; const used = game.phase === 'explore' && (i < game.exploreTurn || i === game.exploreTurn && game.afterPlace); const id = used ? undefined : game.track[i - offset]; return <div key={i}><motion.span key={`${presentation?.id ?? 'rest'}-${step?.kind === 'track' ? 'track' : 'rest'}-${i}`} data-track-token={i} className={`tribe ${id === undefined ? 'empty' : ''}`} style={{ backgroundColor: id === undefined ? undefined : tribes[id], visibility: !reduced && presentation?.action?.type === 'place' && i === presentation.before.exploreTurn ? 'hidden' : undefined }} initial={step?.kind === 'track' ? { opacity: 0, y: -20 } : false} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduced ? 0 : .22, delay: reduced ? 0 : step?.kind === 'track' ? i * .08 : 0 }}>{id === undefined ? '' : game.players[id].name.charAt(0).toUpperCase()}</motion.span><small>{i + 1}</small></div> })}</div>
      <h3 className="camp-heading">Camp</h3><div className="scene-camp">{game.market.map((card, i) => <CampCard key={i} card={card} onClick={() => setPanel('camp')}/>)}<button className="camp-deck" onClick={() => setPanel('camp')} aria-label={`Camp deck, ${game.campDeck.length} cards`}>Deck<span>♧</span></button><small>Discard · {game.campDiscard.length}</small></div>
      <div className="scene-instruction">{preparing ? (['read', 'review'].includes(step?.kind ?? '') ? 'Read before continuing.' : <button onClick={finish}>Skip movement</button>) : <><span>{presentation ? presentation.message : input.phase === 'explore' && !input.afterPlace ? 'Choose a highlighted space on the board.' : input.event}</span><button onClick={() => setPanel(panel === 'actions' ? null : 'actions')}>Choices</button><button onClick={() => setPanel('guide')}>Guide</button>{presentation && <button onClick={finish}>Skip</button>}</>}</div>
      {(step?.kind === 'deal' || step?.kind === 'review') && !comparison && <><div className="scene-dim"/><section className="scene-overlay deal-panel" aria-label="This round's villagers"><header><h1>Meet this round’s villagers</h1><span>{focusCards.length} / {presentation!.after.display.length}</span></header><div className="comparison-grid">{focusCards.map((v, i) => <motion.div key={v.id} initial={{ rotateY: -90, opacity: 0 }} animate={{ rotateY: 0, opacity: 1 }} transition={{ duration: reduced ? 0 : .36 }}><Card villager={v}/>{i === focusCards.length - 1 && step.kind === 'deal' && <span className="sr-only">Just revealed</span>}</motion.div>)}</div>{step.kind === 'review' && <button autoFocus className="primary" onClick={finish}>Continue</button>}</section></>}
      {step?.kind === 'settle' && !comparison && <div className="settlement-layer" aria-hidden="true">{focusCards.map((v, i) => <motion.div key={v.id} className="settling-card" initial={{ left: `${12.7 + (i % 3) * 25.3}%`, top: `${17 + Math.floor(i / 3) * 27}%`, width: '24%', height: '25%' }} animate={{ left: `${1.56 + (i % 3) * 8.88}%`, top: `${78.33 + Math.floor(i / 3) * 10.37}%`, width: '8.1%', height: '9.44%' }} transition={{ duration: reduced ? 0 : .55, delay: reduced ? 0 : i * .07 }}><Card villager={v}/></motion.div>)}</div>}
      {step?.kind === 'read' && !comparison && <><div className="scene-dim"/><section className="scene-overlay faerie-panel" role="dialog" aria-modal="false" aria-labelledby="new-faerie-title"><span className="eyebrow">NEW FAERIE · ROUND {game.round}</span><motion.div className="faerie-emblem" key={`${presentation?.preparation?.index}`} initial={{ scale: .85, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: reduced ? 0 : .25 }}>{fairySymbol(step.fairy!)}</motion.div><h1 id="new-faerie-title">{step.fairy} Faerie</h1><p>{fairyEffects[step.fairy!]}</p><button autoFocus className="primary" onClick={finish}>OK</button><small>Then place at the {game.fairySites.find(s => s.id === step.site)?.kind === 'stump' ? 'stump' : 'statue'}.</small></section></>}
      {comparison && <><div className="scene-dim comparison-dim"/><section className="scene-overlay comparison" role="dialog" aria-modal="true" aria-labelledby="comparison-title"><header><h1 id="comparison-title">Available villagers</h1><span>{game.display.length} choices</span><button ref={compareClose} className="close-overlay" aria-label="Close available villagers" onClick={() => setComparison(null)}>×</button></header><div className="comparison-grid">{game.display.map(v => <Card key={v.id} villager={v} selected={v.id === comparison}>{!presentation && humanTurn && input.phase === 'recruit' && !input.recruitedThisSlot && !input.pendingDraws && <button className="primary" onClick={() => { props.recruit(v.id); setComparison(null) }}>Recruit {v.name}</button>}</Card>)}</div>{!game.display.length && <p>{preparing ? 'Villagers are still being revealed.' : 'No available villagers remain this round.'}</p>}<footer><span>Compare pearl sockets, recruitment rewards and scoring.</span><button onClick={() => setComparison(null)}>Close</button></footer></section></>}
      {showActions && <section className="scene-overlay choices-panel"><button className="close-overlay" aria-label="Close choices" onClick={() => setPanel(null)}>×</button><div inert={!!presentation || undefined}>{humanTurn && input.phase === 'deliver' && <button onClick={() => { if (who !== null) expand(who) }}>Open your village</button>}{humanTurn && input.phase === 'recruit' && !input.recruitedThisSlot && <button onClick={() => setComparison(game.display[0]?.id ?? 'all')}>Compare available villagers</button>}{humanTurn && input.phase === 'deliver' && who !== null && <div className="cargo-controls" aria-label="Choose a carried pearl">{input.players[who].alpaca.map((color, i) => <button key={i} aria-pressed={props.selectedPearl === i} onClick={() => { expand(who); props.selectCargo(i) }}><PearlChip color={color}/>{color}</button>)}</div>}{props.actions}{input.phase === 'explore' && !input.afterPlace && !input.pendingDraws && <details><summary>Choose a board space from a list</summary><div className="slot-list">{input.slots.filter(s => props.legal.has(s.id)).map(s => <button key={s.id} onClick={() => { props.choose(s); setPanel(null) }}>{slotLabel(s)}</button>)}</div></details>}</div></section>}
      {panel && ['settings', 'guide', 'camp'].includes(panel) && !comparison && <section className="scene-overlay utility-panel"><button className="close-overlay" aria-label="Close panel" onClick={() => setPanel(null)}>×</button>{panel === 'settings' ? <><h1>Game settings</h1><label><input type="checkbox" checked={animations} onChange={e => props.setAnimations(e.target.checked)}/> Animations</label><div className="scene-navigation">{props.navigation}</div></> : panel === 'guide' ? <><h1>River guide</h1>{props.guide}</> : <><h1>Camp cards</h1>{campTypes.map(c => <p key={c}><strong>{c}</strong><br/>{campInfo[c].description}</p>)}<p>When gaining cards, choose a face-up card or the deck in Choices.</p></>}</section>}
      {input.phase === 'finished' && <section className="scene-overlay utility-panel"><h1>Journey complete</h1>{props.scores}<div className="scene-navigation">{props.navigation}</div></section>}
      {props.error && <div className="scene-error" role="alert">{props.error}</div>}
    </section>
    <aside className={`player-rail ${player ? 'expanded' : ''}`} aria-label={player ? `${player.name}'s expanded player column` : 'Player llama boards'}>
      {player ? <>{mat(player.id, true)}<section className="rail-fairies"><header>Faeries <small>{player.fairies.length} available</small></header><div>{player.fairies.map((f, i) => <button key={i} title={fairyEffects[f]} onClick={() => setFairy(fairy === f ? null : f)}>{fairySymbol(f)} {f}</button>)}</div></section><section className="rail-hand"><header>Cards <small>{player.hand.length} {player.bot ? 'hidden' : 'cards'}</small></header><div className="rail-hand-grid">{player.bot ? Array.from({ length: Math.min(player.hand.length, 6) }, (_, i) => <div key={i} className="hidden-card" aria-label="Hidden Camp card">🔒</div>) : campTypes.filter(c => player.hand.includes(c)).map(c => <button key={c} title={campInfo[c].description} onClick={() => setPanel('camp')}><img src={campInfo[c].image} alt={c}/><b>×{player.hand.filter(card => card === c).length}</b><span>{c}</span></button>)}</div></section><header className="rail-village-title">Villagers <small>{player.villagers.length} shown · {player.bot ? 'public' : 'owned'}</small></header><div className={`rail-villagers ${player.villagers.length > 8 ? 'dense' : ''}`}>{player.villagers.map(v => <div key={v.id} className="rail-villager" data-owned-villager={v.id}>{player.villagers.length > 8 ? <button onClick={() => setDetail(detail === v.id ? null : v.id)}><img src={assetUrl(v.portrait)} alt=""/><strong>{v.name}</strong><span>{v.stored.filter(Boolean).length}/{v.sockets.length}</span></button> : <>{props.renderVillager(v, !presentation && !comparison && player.id === who && humanTurn && input.phase === 'deliver')}<button className="rail-inspect" aria-label={`Inspect ${v.name}, ${v.stored.filter(Boolean).length} of ${v.sockets.length} sockets filled`} onClick={() => setDetail(detail === v.id ? null : v.id)}/></>}</div>)}</div>{detail && <div className="rail-detail"><button aria-label="Close villager detail" onClick={() => setDetail(null)}>×</button>{player.villagers.filter(v => v.id === detail).map(v => <div key={v.id}>{props.renderVillager(v, !presentation && !comparison && player.id === who && humanTurn && input.phase === 'deliver')}</div>)}</div>}{fairy && <div className="rail-detail"><button aria-label="Close faerie detail" onClick={() => setFairy(null)}>×</button><h3>{fairy} Faerie</h3><p>{fairyEffects[fairy]}</p></div>}</> : game.players.map(p => mat(p.id))}
    </aside><div className="pearl-legend">{colors.map(c => <span key={c}><PearlChip color={c}/>{pearlPoints[c]}</span>)}</div>
  </main>
}
